### ISSUE TITLE
External Servers Are Not Working

### ISSUE THREAD

**Issue by lteresi01** [titaniumnetwork-dev/Phoenix-Reborn#3]
It keeps showing this image when I try the servers:
![image](https://user-images.githubusercontent.com/58713082/76211955-c3458000-61dd-11ea-9611-f4d06736638a.png)

https://beep.meeps.us/external5.html is also not working

**Comment by Harp3rDev** [comment]
Titanium network dev doesn't own the external servers. You can take one of the servers from there, like "http://www.everyday-reluctance-heal-jointly.cf/textbooks/{url}", or just deploy your own node unblocker server.

**Comment by LQ16** [comment]
You have to use your own Node Unblocker servers since the fork you make of this repository is private and thus has to be maintained by you.
