### ISSUE TITLE
Chatbox

### ISSUE THREAD

**Issue by collin9ex** [titaniumnetwork-dev/phoenix-reborn#8]
Titanembeds not working. It freezes here:
![Screenshot 2019-05-20 at 7 37 18 AM](https://user-images.githubusercontent.com/36419194/58018899-1e34ac00-7ad2-11e9-876e-49283d48a81b.png)

**Comment by Shadowsnhd** [comment]
it was disabled for a couple days due to abuse.

I've re-enabled it.

**Comment by collin9ex** [comment]
k
